## Preparation of final dataset
1. Loading files for Transport and Industry
2. Process industry data per subsector (Steel, Basic Chemicals, NMM)
3. Process transport data per subsectors and fuels (Electricity, Hydrogen, Gases, Liquids)
4. Prepare final excel file with one per each year and country merging all values

In [ ]:
import pandas as pd
from collections import defaultdict
import os

:

1. Loading files for Transport and Industry

In [1216]:
transport_file = os.path.join('..', 'REMIND', 'Results_REMIND_JRC.csv')
industry_path = os.path.join('Industry', 'Results_per_Country')

In [1217]:
country_code = "SK"
# ['EU27', 'AT', 'BE', 'BG', 'CY', 
# 'CZ', 'DE', 'DK', 'EE', 'EL', 'ES', 'FI', 'FR', 'HR', 
# 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'MT', 'NL', 'PL', 
# 'PT', 'RO', 'SE', 'SI', 'SK']

years = [2030, 2040, 2050]

In [ ]:
output_path = os.path.join('..', 'Outputs', f'PtX_demand_{country_code}.csv')

In [1219]:
def load_transport_data(filepath):
    df = pd.read_csv(filepath)
    df['Year'] = df['Year'].astype(int)
    return df

In [1220]:
def load_industry_data(filepath):
    industry_data = []
    industry_files = [f for f in os.listdir(filepath) if f.endswith(".xlsx")]

    for file_name in industry_files:
        year, country = file_name.replace(".xlsx", "").split("_")
        file_path = os.path.join(filepath, file_name)
        df = pd.read_excel(file_path, index_col=0)
        df = df.apply(pd.to_numeric, errors='coerce').fillna(0)

        for material in df.index:
            for sector in df.columns:
                industry_data.append({
                    "Year": int(year),
                    "Country": country,
                    "Category": sector,
                    "Material": material.strip(),
                    "Value": df.loc[material, sector] * 3.6 * 0.000001
                })

    return pd.DataFrame(industry_data)

In [1221]:
transport_df = load_transport_data(transport_file)
industry_df = load_industry_data(industry_path)

2. Process industry data per subsector (Steel, Basic Chemicals, NMM)

In [1222]:
industry_mapping = {
    'Overall Demand': 'Overall Demand',
    'Power': 'Power',   
    'Hydrogen': 'Hydrogen',
    'Ammonia': 'Ammonia',
    'Methanol': 'Methanol',
    'Biomass': 'Biomass [Solid]',
    'Biogas': 'Biogenic Gases',
    'Fossil Rest': 'Fossil Residuals',
    'Other': 'Renewable Energy Carrier',
}

In [1223]:
industry_output = defaultdict(lambda: defaultdict(float))

In [1224]:
industry_filtered = industry_df[industry_df["Country"] == country_code]

In [1225]:

for _, row in industry_filtered.iterrows():
    year = row["Year"]
    mat = row["Material"]
    fuel = industry_mapping.get(mat)
    if fuel:
        key = (fuel, year)
        industry_output[key][row["Category"]] += row["Value"]

In [1226]:
industry_rows = []

for (fuel_group, year), sectors in industry_output.items():
    for sector, value in sectors.items():
        industry_rows.append({
            "FuelGroup": fuel_group,
            "Year": year,
            "IndustrySector": sector,
            "Value": value if value != 0 else None 
        })

industry_df = pd.DataFrame(industry_rows)

In [1227]:
pivot_industry = industry_df.pivot_table(
    index=["FuelGroup", "Year"],
    columns="IndustrySector",
    values="Value",
    aggfunc="sum"
).reset_index()
pivot_industry

IndustrySector,FuelGroup,Year,Chemicals,Iron & steel,Non-metallic minerals
0,Ammonia,2030,6.592285e-03,0.000000,0.000000
1,Ammonia,2040,6.415952e-03,0.000000,0.000000
2,Ammonia,2050,6.266574e-03,0.000000,0.000000
3,Biogenic Gases,2030,0.000000e+00,0.000000,0.000550
4,Biogenic Gases,2040,0.000000e+00,0.000000,0.002078
5,Biogenic Gases,2050,0.000000e+00,0.000000,0.004940
6,Biomass [Solid],2030,0.000000e+00,0.000000,0.002119
7,Biomass [Solid],2040,0.000000e+00,0.000000,0.001955
8,Biomass [Solid],2050,0.000000e+00,0.000000,0.001822
9,Fossil Residuals,2030,1.278977e-20,0.026367,0.009492
10,Fossil Residuals,2040,0.000000e+00,0.017771,0.006037
11,Fossil Residuals,2050,0.000000e+00,0.000000,0.000000
12,Hydrogen,2030,0.000000e+00,0.002930,0.000000
13,Hydrogen,2040,0.000000e+00,0.011847,0.000000
14,Hydrogen,2050,0.000000e+00,0.029890,0.000000
15,Methanol,2030,3.699259e-05,0.000000,0.000000
16,Methanol,2040,3.600310e-05,0.000000,0.000000
17,Methanol,2050,3.516487e-05,0.000000,0.000000
18,Overall Demand,2030,1.034663e-02,0.037358,0.013472
19,Overall Demand,2040,9.909779e-03,0.037632,0.012804
20,Overall Demand,2050,9.539703e-03,0.037864,0.012242
21,Power,2030,3.717354e-03,0.008061,0.000805
22,Power,2040,3.457824e-03,0.008014,0.000787
23,Power,2050,3.237964e-03,0.007974,0.000772
24,Renewable Energy Carrier,2030,0.000000e+00,0.000000,0.000505
25,Renewable Energy Carrier,2040,0.000000e+00,0.000000,0.001947
26,Renewable Energy Carrier,2050,0.000000e+00,0.000000,0.004709

3. Process transport data per subsectors and fuels (Electricity, Hydrogen, Gases, Liquids)

In [1228]:
fuel_map = {
    'Liquids|Biomass': 'Biogenic Liquids',
    'Gases|Biomass': 'Biogenic Gases',
    'Liquids|Hydrogen': 'Synthetic Liquids',
    'Gases|Hydrogen': 'Synthetic Gases',
    'Hydrogen': 'Hydrogen',
    
    # Added Fossil Categories
    'Liquids|Fossil': 'Fossil Liquids',
    'Gases|Fossil': 'Fossil Gases',

    # Add power
    'Electricity': 'Power',
}

In [1229]:
transport_output = defaultdict(lambda: defaultdict(float))

In [1230]:
categories = [
    "FE|Transport|Freight|Road|Heavy",
    "FE|Transport|Freight|Road|Light",
    "FE|Transport|Pass|Road|Bus",
    "FE|Transport|Pass|Road|LDV|Four Wheelers",
    "FE|Transport|Pass|Road|LDV|Two Wheelers",
    "FE|Transport|Pass|Domestic Aviation",
    "FE|Transport|Pass|Aviation",
    "FE|Transport|Pass|Rail",
    "FE|Transport|Freight|Rail",
    "FE|Transport|Bunkers|Freight|International Shipping",
    "FE|Transport|Freight|Domestic Shipping"               
]

main_category_mapping = {
    "FE|Transport|Freight|Road|Heavy": "Road",
    "FE|Transport|Freight|Road|Light": "Road",
    "FE|Transport|Pass|Road|Bus": "Road",
    "FE|Transport|Pass|Road|LDV|Four Wheelers": "Road",
    "FE|Transport|Pass|Road|LDV|Two Wheelers": "Road",
    "FE|Transport|Pass|Domestic Aviation": "Aviation",
    "FE|Transport|Pass|Aviation": "Aviation",
    "FE|Transport|Pass|Rail": "Rail",
    "FE|Transport|Freight|Rail": "Rail",
    "FE|Transport|Bunkers|Freight|International Shipping": "Shipping",
    "FE|Transport|Freight|Domestic Shipping": "Shipping"
}

transport_fuel_paths = [
    # Freight Road Heavy
    "FE|Transport|Freight|Road|Heavy|Electricity",
    "FE|Transport|Freight|Road|Heavy|Hydrogen",
    "FE|Transport|Freight|Road|Heavy|Gases",
    "FE|Transport|Freight|Road|Heavy|Gases|Biomass",
    "FE|Transport|Freight|Road|Heavy|Gases|Fossil",
    "FE|Transport|Freight|Road|Heavy|Gases|Hydrogen",
    "FE|Transport|Freight|Road|Heavy|Liquids",
    "FE|Transport|Freight|Road|Heavy|Liquids|Biomass",
    "FE|Transport|Freight|Road|Heavy|Liquids|Fossil",
    "FE|Transport|Freight|Road|Heavy|Liquids|Hydrogen",

    # Freight Road Light
    "FE|Transport|Freight|Road|Light|Electricity",
    "FE|Transport|Freight|Road|Light|Hydrogen",
    "FE|Transport|Freight|Road|Light|Gases",
    "FE|Transport|Freight|Road|Light|Gases|Biomass",
    "FE|Transport|Freight|Road|Light|Gases|Fossil",
    "FE|Transport|Freight|Road|Light|Gases|Hydrogen",
    "FE|Transport|Freight|Road|Light|Liquids",
    "FE|Transport|Freight|Road|Light|Liquids|Biomass",
    "FE|Transport|Freight|Road|Light|Liquids|Fossil",
    "FE|Transport|Freight|Road|Light|Liquids|Hydrogen",

    # Passenger Road Bus
    "FE|Transport|Pass|Road|Bus|Electricity",
    "FE|Transport|Pass|Road|Bus|Hydrogen",
    "FE|Transport|Pass|Road|Bus|Gases",
    "FE|Transport|Pass|Road|Bus|Gases|Biomass",
    "FE|Transport|Pass|Road|Bus|Gases|Fossil",
    "FE|Transport|Pass|Road|Bus|Gases|Hydrogen",
    "FE|Transport|Pass|Road|Bus|Liquids",
    "FE|Transport|Pass|Road|Bus|Liquids|Biomass",
    "FE|Transport|Pass|Road|Bus|Liquids|Fossil",
    "FE|Transport|Pass|Road|Bus|Liquids|Hydrogen",

    # Passenger Road LDV Four Wheelers
    "FE|Transport|Pass|Road|LDV|Four Wheelers|Electricity",
    "FE|Transport|Pass|Road|LDV|Four Wheelers|Hydrogen",
    "FE|Transport|Pass|Road|LDV|Four Wheelers|Gases",
    "FE|Transport|Pass|Road|LDV|Four Wheelers|Gases|Biomass",
    "FE|Transport|Pass|Road|LDV|Four Wheelers|Gases|Fossil",
    "FE|Transport|Pass|Road|LDV|Four Wheelers|Gases|Hydrogen",
    "FE|Transport|Pass|Road|LDV|Four Wheelers|Liquids",
    "FE|Transport|Pass|Road|LDV|Four Wheelers|Liquids|Biomass",
    "FE|Transport|Pass|Road|LDV|Four Wheelers|Liquids|Fossil",
    "FE|Transport|Pass|Road|LDV|Four Wheelers|Liquids|Hydrogen",

    # Passenger Road LDV Two Wheelers
    "FE|Transport|Pass|Road|LDV|Two Wheelers|Electricity",
    "FE|Transport|Pass|Road|LDV|Two Wheelers|Liquids",
    "FE|Transport|Pass|Road|LDV|Two Wheelers|Liquids|Biomass",
    "FE|Transport|Pass|Road|LDV|Two Wheelers|Liquids|Fossil",
    "FE|Transport|Pass|Road|LDV|Two Wheelers|Liquids|Hydrogen",

    # Bunkers Freight International Shipping
    "FE|Transport|Bunkers|Freight|International Shipping|Liquids",

    # Freight Domestic Shipping
    "FE|Transport|Freight|Domestic Shipping|Liquids",
    "FE|Transport|Freight|Domestic Shipping|Liquids|Biomass",
    "FE|Transport|Freight|Domestic Shipping|Liquids|Fossil",
    "FE|Transport|Freight|Domestic Shipping|Liquids|Hydrogen",

    # Bunkers Pass International Aviation
    "FE|Transport|Bunkers|Pass|International Aviation|Liquids",

    # Passenger Domestic Aviation
    "FE|Transport|Pass|Domestic Aviation|Electricity",
    "FE|Transport|Pass|Domestic Aviation|Hydrogen",
    "FE|Transport|Pass|Domestic Aviation|Liquids",
    "FE|Transport|Pass|Domestic Aviation|Liquids|Biomass",
    "FE|Transport|Pass|Domestic Aviation|Liquids|Fossil",
    "FE|Transport|Pass|Domestic Aviation|Liquids|Hydrogen",

    # Passenger Aviation
    "FE|Transport|Pass|Aviation|Electricity",
    "FE|Transport|Pass|Aviation|Hydrogen",
    "FE|Transport|Pass|Aviation|Liquids",
    "FE|Transport|Pass|Aviation|Liquids|Biomass",
    "FE|Transport|Pass|Aviation|Liquids|Fossil",
    "FE|Transport|Pass|Aviation|Liquids|Hydrogen",

    # Passenger Rail
    "FE|Transport|Pass|Rail|Electricity",
    "FE|Transport|Pass|Rail|Hydrogen",
    "FE|Transport|Pass|Rail|Liquids",
    "FE|Transport|Pass|Rail|Liquids|Biomass",
    "FE|Transport|Pass|Rail|Liquids|Fossil",
    "FE|Transport|Pass|Rail|Liquids|Hydrogen",

    # Freight Rail
    "FE|Transport|Freight|Rail|Electricity",
    "FE|Transport|Freight|Rail|Hydrogen",
    "FE|Transport|Freight|Rail|Liquids", 
    "FE|Transport|Freight|Rail|Liquids|Biomass",
    "FE|Transport|Freight|Rail|Liquids|Fossil",
    "FE|Transport|Freight|Rail|Liquids|Hydrogen",
]

In [1231]:
def extract_main_and_fuel(category_str, categories):
    categories_sorted = sorted(categories, key=len, reverse=True)
    
    for cat_prefix in categories_sorted:
        if category_str.startswith(cat_prefix):
            # Fuel is whatever comes after the prefix (skip the '|')
            remainder = category_str[len(cat_prefix):]
            if remainder.startswith("|"):
                remainder = remainder[1:]  # remove leading '|'
            return cat_prefix, remainder
    # If no prefix matched, return None and full string as fuel
    return None, category_str

In [1232]:
transport_filtered = transport_df[(transport_df["Country"] == country_code) & 
                                  (transport_df["Year"].isin(years))]

In [1233]:
transport_filtered[["MainCategory", "Fuel"]] = transport_filtered["Category"].apply(lambda x: pd.Series(extract_main_and_fuel(x, categories)))
fuel_transport = transport_filtered[(transport_filtered["Fuel"].notna()) & 
                              (transport_filtered["Country"] == country_code)]

C:\Users\mar.eco\AppData\Local\Temp\ipykernel_9504\1015843666.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transport_filtered[["MainCategory", "Fuel"]] = transport_filtered["Category"].apply(lambda x: pd.Series(extract_main_and_fuel(x, categories)))
C:\Users\mar.eco\AppData\Local\Temp\ipykernel_9504\1015843666.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transport_filtered[["MainCategory", "Fuel"]] = transport_filtered["Category"].apply(lambda x: pd.Series(extract_main_and_fuel(x, categories)))

In [1234]:
main_category_mapping = {
    "FE|Transport|Freight|Road|Heavy": "Freight Road",
    "FE|Transport|Freight|Road|Light": "Freight Road",
    "FE|Transport|Pass|Road|Bus": "Pass Road",
    "FE|Transport|Pass|Road|LDV|Four Wheelers": "Pass Road",
    "FE|Transport|Pass|Road|LDV|Two Wheelers": "Pass Road",
    "FE|Transport|Pass|Domestic Aviation": "Pass Aviation",
    "FE|Transport|Pass|Aviation": "Pass Aviation",
    "FE|Transport|Pass|Rail": "Pass Rail",
    "FE|Transport|Freight|Rail": "Freight Rail",
    "FE|Transport|Bunkers|Freight|International Shipping": "Maritime",
    "FE|Transport|Freight|Domestic Shipping": "Maritime",
}

In [1235]:
fuel_transport["TransportSector"] = fuel_transport["MainCategory"].map(main_category_mapping)

In [1236]:
fuel_transport["FuelGroup"] = fuel_transport["Fuel"].map(fuel_map)

In [1237]:
fuel_transport = fuel_transport[fuel_transport["FuelGroup"].notna()]

In [1238]:
agg_transport = fuel_transport.groupby(
    ["Year", "FuelGroup", "TransportSector"]
)["Value"].sum().reset_index()

In [1239]:
pivot_transport = agg_transport.pivot_table(
    index=["FuelGroup", "Year"],
    columns="TransportSector",
    values="Value",
    aggfunc="sum"
).reset_index()
pivot_transport

TransportSector,FuelGroup,Year,Freight Rail,Freight Road,Maritime,Pass Aviation,Pass Rail,Pass Road
0,Biogenic Gases,2030,NaN,1.939025e-05,NaN,NaN,NaN,6.470281e-05
1,Biogenic Gases,2040,NaN,2.861930e-05,NaN,NaN,NaN,7.782333e-05
2,Biogenic Gases,2050,NaN,7.875354e-06,NaN,NaN,NaN,1.413917e-05
3,Biogenic Liquids,2030,1.421048e-04,3.069142e-03,7.395552e-05,2.063536e-04,4.319299e-05,3.515587e-03
4,Biogenic Liquids,2040,1.726342e-04,2.086658e-03,9.711916e-05,2.512060e-04,7.041169e-05,1.575217e-03
5,Biogenic Liquids,2050,2.220349e-04,5.427956e-04,1.318973e-04,3.290257e-04,1.258133e-04,1.622106e-04
6,Fossil Gases,2030,NaN,6.639033e-05,NaN,NaN,NaN,7.299738e-04
7,Fossil Gases,2040,NaN,7.161272e-05,NaN,NaN,NaN,4.012077e-04
8,Fossil Gases,2050,NaN,2.493562e-05,NaN,NaN,NaN,2.829770e-05
9,Fossil Liquids,2030,8.601604e-04,1.981416e-02,5.287308e-04,1.885960e-03,3.041955e-04,3.388154e-02
10,Fossil Liquids,2040,7.633154e-04,9.130467e-03,4.665094e-04,1.778108e-03,3.270271e-04,9.396000e-03
11,Fossil Liquids,2050,6.570244e-04,1.595984e-03,3.828920e-04,1.612515e-03,2.949646e-04,4.874017e-04
12,Hydrogen,2030,NaN,7.787658e-05,NaN,7.541897e-11,NaN,1.895260e-04
13,Hydrogen,2040,NaN,1.218732e-04,NaN,6.313401e-09,NaN,9.064259e-04
14,Hydrogen,2050,NaN,1.962838e-04,NaN,1.070071e-08,NaN,1.259330e-03
15,Power,2030,1.287774e-03,1.314333e-03,NaN,NaN,1.749010e-03,4.084074e-03
16,Power,2040,1.270045e-03,4.938365e-03,NaN,NaN,2.052624e-03,1.165676e-02
17,Power,2050,1.297127e-03,7.646782e-03,NaN,NaN,2.305085e-03,1.362990e-02
18,Synthetic Gases,2030,NaN,0.000000e+00,NaN,NaN,NaN,0.000000e+00
19,Synthetic Gases,2040,NaN,4.145795e-11,NaN,NaN,NaN,3.389393e-10
20,Synthetic Gases,2050,NaN,1.349076e-09,NaN,NaN,NaN,3.774845e-09
21,Synthetic Liquids,2030,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
22,Synthetic Liquids,2040,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
23,Synthetic Liquids,2050,1.182342e-12,3.255382e-11,1.636069e-11,9.678284e-12,2.592882e-12,7.208651e-12

4. Prepare final excel file with one per each year and country merging all values

In [1240]:
pivot_transport = pivot_transport.rename(columns={"TransportSector": "SectorGroup"})
pivot_industry = pivot_industry.rename(columns={"FuelGroup": "FuelGroup", "Year": "Year"})

In [1241]:
pivot_industry["SectorGroup"] = "Industry"
pivot_transport["SectorGroup"] = "Transport"

In [1242]:
column_order = [
    "Iron & steel", "Chemicals", "Non-metallic minerals",  # Industry
    "Pass Road", "Pass Rail", "Pass Aviation",             # Transport (passenger)
    "Freight Road", "Freight Rail",                        # Transport (freight)
    "Maritime"                                             # Maritime (bunkers)
]

In [1243]:
all_columns = set(column_order + ["FuelGroup", "Year", "SectorGroup"])

# Add missing columns as None
for col in all_columns:
    if col not in pivot_transport.columns:
        pivot_transport[col] = None
    if col not in pivot_industry.columns:
        pivot_industry[col] = None

In [1244]:
combined_df = pd.concat([pivot_transport, pivot_industry], ignore_index=True)

C:\Users\mar.eco\AppData\Local\Temp\ipykernel_9504\4054876749.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([pivot_transport, pivot_industry], ignore_index=True)

In [1245]:
# Ignore Overall Demand in this step
fuel_order = [
    "Power", "Hydrogen", "Methanol", "Ammonia", 
    "Synthetic Gases", "Biogenic Gases", "Fossil Gases",
    "Synthetic Liquids", "Biogenic Liquids", "Fossil Liquids",
    "Fossil Residuals", "Biomass [Solid]", "Renewable Energy Carrier"
]

In [1246]:
for year in [2030, 2040, 2050]:
    # Calculate the sum for EVERY column (Industry AND Transport) for that year
    sector_totals = combined_df[(combined_df["Year"] == year) & 
                             (combined_df["FuelGroup"].isin(fuel_order))][column_order].sum()
    
    # Place that sum into the "Overall Demand" row for that year
    combined_df.loc[(combined_df["Year"] == year) & 
                 (combined_df["FuelGroup"] == "Overall Demand"), column_order] = sector_totals.values

In [1247]:
fuel_order_map = {fuel: i for i, fuel in enumerate(fuel_order)}
combined_df["FuelSortOrder"] = combined_df["FuelGroup"].map(fuel_order_map)

In [1248]:
final_df = combined_df.drop(columns=["SectorGroup", "FuelSortOrder"])  # drop SectorGroup
final_df = final_df.groupby(["FuelGroup", "Year"], as_index=False).sum()

In [1249]:
def clean_zeros_and_nans(df):
    return df.applymap(lambda x: "" if pd.isna(x) or x == 0 else x)

In [1250]:
clean_df = clean_zeros_and_nans(final_df)

C:\Users\mar.eco\AppData\Local\Temp\ipykernel_9504\2748423523.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) or x == 0 else x)

In [1251]:
ordered_cols = ["FuelGroup", "Year"] + column_order
final_correct_order = clean_df[ordered_cols]
final_correct_order["FuelSortOrder"] = final_correct_order["FuelGroup"].map(fuel_order_map)
final_correct_order = final_correct_order.sort_values(by=["Year", "FuelSortOrder"]).drop(columns=["FuelSortOrder"])
final_correct_order

C:\Users\mar.eco\AppData\Local\Temp\ipykernel_9504\2721408278.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_correct_order["FuelSortOrder"] = final_correct_order["FuelGroup"].map(fuel_order_map)

,FuelGroup,Year,Iron & steel,Chemicals,Non-metallic minerals,Pass Road,Pass Rail,Pass Aviation,Freight Road,Freight Rail,Maritime
30,Power,2030,0.008061,0.003717,0.000805,0.004084,0.001749,,0.001314,0.001288,
21,Hydrogen,2030,0.00293,,,0.00019,,0.0,0.000078,,
24,Methanol,2030,,0.000037,,,,,,,
0,Ammonia,2030,,0.006592,,,,,,,
36,Synthetic Gases,2030,,,,,,,,,
3,Biogenic Gases,2030,,,0.00055,0.000065,,,0.000019,,
12,Fossil Gases,2030,,,,0.00073,,,0.000066,,
39,Synthetic Liquids,2030,,,,,,,,,
6,Biogenic Liquids,2030,,,,0.003516,0.000043,0.000206,0.003069,0.000142,0.000074
15,Fossil Liquids,2030,,,,0.033882,0.000304,0.001886,0.019814,0.00086,0.000529
18,Fossil Residuals,2030,0.026367,0.0,0.009492,,,,,,
9,Biomass [Solid],2030,,,0.002119,,,,,,
33,Renewable Energy Carrier,2030,,,0.000505,,,,,,
27,Overall Demand,2030,0.037358,0.010347,0.013472,0.042465,0.002096,0.002092,0.024361,0.00229,0.000603
31,Power,2040,0.008014,0.003458,0.000787,0.011657,0.002053,,0.004938,0.00127,
22,Hydrogen,2040,0.011847,,,0.000906,,0.0,0.000122,,
25,Methanol,2040,,0.000036,,,,,,,
1,Ammonia,2040,,0.006416,,,,,,,
37,Synthetic Gases,2040,,,,0.0,,,0.0,,
4,Biogenic Gases,2040,,,0.002078,0.000078,,,0.000029,,
13,Fossil Gases,2040,,,,0.000401,,,0.000072,,
40,Synthetic Liquids,2040,,,,,,,,,
7,Biogenic Liquids,2040,,,,0.001575,0.00007,0.000251,0.002087,0.000173,0.000097
16,Fossil Liquids,2040,,,,0.009396,0.000327,0.001778,0.00913,0.000763,0.000467
19,Fossil Residuals,2040,0.017771,,0.006037,,,,,,
10,Biomass [Solid],2040,,,0.001955,,,,,,
34,Renewable Energy Carrier,2040,,,0.001947,,,,,,
28,Overall Demand,2040,0.037632,0.00991,0.012804,0.024013,0.00245,0.002029,0.016378,0.002206,0.000564
32,Power,2050,0.007974,0.003238,0.000772,0.01363,0.002305,,0.007647,0.001297,
23,Hydrogen,2050,0.02989,,,0.001259,,0.0,0.000196,,
26,Methanol,2050,,0.000035,,,,,,,
2,Ammonia,2050,,0.006267,,,,,,,
38,Synthetic Gases,2050,,,,0.0,,,0.0,,
5,Biogenic Gases,2050,,,0.00494,0.000014,,,0.000008,,
14,Fossil Gases,2050,,,,0.000028,,,0.000025,,
41,Synthetic Liquids,2050,,,,0.0,0.0,0.0,0.0,0.0,0.0
8,Biogenic Liquids,2050,,,,0.000162,0.000126,0.000329,0.000543,0.000222,0.000132
17,Fossil Liquids,2050,,,,0.000487,0.000295,0.001613,0.001596,0.000657,0.000383
20,Fossil Residuals,2050,,,,,,,,,
11,Biomass [Solid],2050,,,0.001822,,,,,,
35,Renewable Energy Carrier,2050,,,0.004709,,,,,,
29,Overall Demand,2050,0.037864,0.00954,0.012242,0.015581,0.002726,0.001942,0.010015,0.002176,0.000515

In [ ]:
final_correct_order.to_csv(output_path, index=False, na_rep="")